# Generated by Django 4.2.7 on 2025-10-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS blog_comment;",
            reverse_sql="-- Cannot reverse DROP TABLE"
        ),
    ]
